{
    'name': "Product Actual Available Qualtity(Community & Enterprise)",
    'version': '13.0.1',
    'summary': """Using this module you can get product actual avaialble quantity in Product and Varient""",
    'description': '''Using this module you can get product actual avaialble quantity in Product and Varient''',
    'category' : 'Product',
    'price': 0,
    'currency': 'EUR',
    "author" : "MAISOLUTIONSLLC",
    'sequence': 1,
    "email": 'apps@maisolutionsllc.com',
    "website":'http://maisolutionsllc.com/',
    'license': 'OPL-1',
    'depends': ['product', 'stock'],
    'data':['views/product_view.xml'],
    'qweb' : [],
    'images': ['static/description/main_screenshot.png'],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}

